
CREATE DATABASE COMMUNITY_SERVICE_PROJECT;  
USE COMMUNITY_SERVICE_PROJECT;
 CREATE TABLE VOLUNTEER(Volunteer_id INT NOT NULL, 
 Volunteer_Name VARCHAR(50), Address VARCHAR(100), Contact VARCHAR(10), PRIMARY KEY(Volunteer_Id),
 CHECK(LENGTH(Contact)=10));
 DESCRIBE VOLUNTEER;

INSERT INTO VOLUNTEER VALUES(NULL,'Kavya','ABC Street','9887766543');
 INSERT INTO VOLUNTEER VALUES(101,'Kavya','ABC Street','98877665');
  INSERT INTO VOLUNTEER VALUES(101,'Kavya','ABC Street','9887766543');
 INSERT INTO VOLUNTEER VALUES(102,'Sri','XYZ Street','7887766543');
 INSERT INTO VOLUNTEER VALUES(103,'Vaipava','PCM 2nd Street','6487766543');
INSERT INTO VOLUNTEER VALUES(104,'Deulin','WWX Street','9487766543');
INSERT INTO VOLUNTEER VALUES(105,'Priya','ZYX Street','8487766543');
INSERT INTO VOLUNTEER VALUES(106,'Surya','ALM Street','8887766543');
 INSERT INTO VOLUNTEER VALUES(107,'Swathi','GHI Street','6887766543');

CREATE TABLE SERVICE_PROJECTS(
PROJECT_ID INT PRIMARY KEY,PROJECT_NAME VARCHAR(20),
PROJECT_DES VARCHAR(100),VOLUNTEER_ID INT NOT NULL,
FOREIGN KEY(VOLUNTEER_ID) REFERENCES VOLUNTEER(VOLUNTEER_ID));
 INSERT INTO SERVICE_PROJECTS VALUES(1,'Service 1','Description about service 1',10);
INSERT INTO SERVICE_PROJECTS VALUES(1,'Service 1','Description about service 1',101);
INSERT INTO SERVICE_PROJECTS VALUES(2,'Service 2','Description about service 2',102);
INSERT INTO SERVICE_PROJECTS VALUES(1,'Service 1','Description about service 3',103);
INSERT INTO SERVICE_PROJECTS VALUES(3,'Service 3','Description about service 3',103);
INSERT INTO SERVICE_PROJECTS VALUES(4,'Service 4','Description about service 4',104);
INSERT INTO SERVICE_PROJECTS VALUES(5,'Service 5','Description about service 5',105);
INSERT INTO SERVICE_PROJECTS VALUES(6,'Service 6','Description about service 6',106);
INSERT INTO SERVICE_PROJECTS VALUES(7,'Service 7','Description about service 7',107);
SELECT * FROM SERVICE_PROJECTS;
CREATE TABLE PROJECT_STATUS
(STATUS_ID INT PRIMARY KEY, STATUS VARCHAR(20),
PROJECT_ID INT, FOREIGN KEY(PROJECT_ID) REFERENCES SERVICE_PROJECTS(PROJECT_ID));
 INSERT INTO PROJECT_STATUS VALUES(10,'Completed',1);
INSERT INTO PROJECT_STATUS VALUES(11,'NOT Completed',2);
INSERT INTO PROJECT_STATUS VALUES(12,'IN PROGRESS',3);
INSERT INTO PROJECT_STATUS VALUES(13,'IN PROGRESS',5);
INSERT INTO PROJECT_STATUS VALUES(14,'IN PROGRESS',4);
 INSERT INTO PROJECT_STATUS VALUES(15,'COMPLETED',6);
 INSERT INTO PROJECT_STATUS VALUES(16,'NOT COMPLETED',7);
 SELECT * FROM PROJECT_STATUS;
CREATE TABLE LOGIN(Login_Id INT PRIMARY KEY,VOLUNTEER_ID INT,FOREIGN KEY(VOLUNTEER_ID)
REFERENCES VOLUNTEER(VOLUNTEER_ID));
INSERT INTO LOGIN VALUES(1001,101);
INSERT INTO LOGIN VALUES(1002,102);
INSERT INTO LOGIN VALUES(1003,103);
INSERT INTO LOGIN VALUES(1004,104);
INSERT INTO LOGIN VALUES(1005,105);
INSERT INTO LOGIN VALUES(1006,106);
INSERT INTO LOGIN VALUES(1007,107);
SELECT * FROM LOGIN;
UPDATE VOLUNTEER SET VOLUNTEER_NAME='KAVS' WHERE VOLUNTEER_ID=101;
SELECT * FROM VOLUNTEER;
 SELECT V.VOLUNTEER_NAME,V.ADDRESS,P.PROJECT_ID,P.PROJECT_NAME FROM 
 VOLUNTEER V JOIN SERVICE_PROJECTS P
 ON V.VOLUNTEER_ID=P.VOLUNTEER_ID;
 CREATE TABLE ADMIN(ADMIN_ID INT PRIMARY KEY,ADMIN_NAME VARCHAR(20));
 INSERT INTO ADMIN VALUES(1,'A1');
  INSERT INTO ADMIN VALUES(2,'A2');
   INSERT INTO ADMIN VALUES(3,'A3');
    INSERT INTO ADMIN VALUES(4,'A4');
    SELECT * FROM ADMIN;
   DELETE FROM ADMIN ADMIN_NAME WHERE ADMIN_ID=1;
 TRUNCATE ADMIN;
 DROP TABLE ADMIN;
 
